#!/bin/bash
# ============================================================
# urwort Deployment Script
#
# Subcommands:
#   plan          — terraform plan only
#   apply         — terraform apply + ansible (full setup)
#   ansible       — full ansible run (server already provisioned)
#   sync          — sync code + rebuild + restart (fast, no system changes)
#   destroy       — terraform destroy
#
# Usage (inside ops container):
#   cd /ops && ./scripts/deploy.sh sync      ← day-to-day code deploys
#   cd /ops && ./scripts/deploy.sh ansible   ← full reconfigure
#   cd /ops && ./scripts/deploy.sh apply     ← first-time infra + deploy
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
TF_DIR="$INFRA_DIR/terraform"
ANSIBLE_DIR="$INFRA_DIR/ansible"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

ACTION="${1:-plan}"

echo -e "${GREEN}━━━ urwort Deployment — ${ACTION} ━━━${NC}"
echo ""

# ── Helper: build ansible extra-vars from environment ─────────────────────────
# All secrets come from .env.ops — nothing hard-coded here.
build_extra_vars() {
    echo "data_dir=${DATA_DIR:-/mnt/urwort-data}"
    # S3 / RunPod — not used by urwort; commented for future reference
    # aws_access_key_id=${AWS_ACCESS_KEY_ID:-}
    # aws_secret_access_key=${AWS_SECRET_ACCESS_KEY:-}
    # aws_endpoint_url=${AWS_ENDPOINT_URL:-}
    # runpod_api_key=${RUNPOD_API_KEY:-}
}

# ── Helper: run ansible using inventory from TF output ────────────────────────
run_ansible() {
    local server_ip="$1"
    local volume_mount="${2:-/mnt/urwort-data}"
    local extra_tags="${3:-}"   # optional --tags value

    echo -e "${YELLOW}Generating Ansible inventory...${NC}"
    cat > "$ANSIBLE_DIR/inventory.yml" << INVENTORY
# Auto-generated by deploy.sh — $(date -Iseconds)
all:
  hosts:
    urwort-server:
      ansible_host: "${server_ip}"
      ansible_user: root
      ansible_ssh_private_key_file: "~/.ssh/urwort_ed25519"
      ansible_ssh_extra_args: "-F /dev/null -o StrictHostKeyChecking=no"
  vars:
    server_ip: "${server_ip}"
    volume_mount: "${volume_mount}"
INVENTORY

    echo "  Inventory written → $ANSIBLE_DIR/inventory.yml"
    echo "  Server IP: $server_ip"
    echo ""

    # Wait for SSH
    echo -e "${YELLOW}Waiting for SSH on ${server_ip}...${NC}"
    for i in $(seq 1 30); do
        if ssh -F /dev/null -i ~/.ssh/urwort_ed25519 \
               -o ConnectTimeout=5 -o StrictHostKeyChecking=no \
               -o BatchMode=yes "root@${server_ip}" true 2>/dev/null; then
            echo -e "  ${GREEN}SSH ready!${NC}"
            break
        fi
        if [ "$i" -eq 30 ]; then
            echo -e "${RED}SSH timeout (150s). Is the server running?${NC}"
            exit 1
        fi
        echo "  attempt $i/30..."
        sleep 5
    done

    echo ""
    echo -e "${YELLOW}Running Ansible playbook...${NC}"
    cd "$ANSIBLE_DIR"

    EXTRA_VARS="$(build_extra_vars)"
    TAGS_ARG=""
    [ -n "$extra_tags" ] && TAGS_ARG="--tags=$extra_tags"
    # shellcheck disable=SC2086
    ansible-playbook -i inventory.yml site.yml \
        --extra-vars "$EXTRA_VARS" $TAGS_ARG

    echo ""
    echo -e "${GREEN}━━━ Ansible complete ━━━${NC}"
    echo -e "App: ${CYAN}http://$(echo "$server_ip" | tr '.' '-').sslip.io${NC}"
}

# ── Subcommands ────────────────────────────────────────────────────────────────

case "$ACTION" in

    plan)
        echo -e "${YELLOW}[Terraform] plan...${NC}"
        cd "$TF_DIR"
        [ ! -d ".terraform" ] && terraform init
        terraform plan
        echo ""
        echo -e "${GREEN}Plan complete. Run './scripts/deploy.sh apply' to proceed.${NC}"
        ;;

    apply)
        echo -e "${YELLOW}[1/2] Terraform apply...${NC}"
        cd "$TF_DIR"
        [ ! -d ".terraform" ] && terraform init
        terraform apply -auto-approve

        SERVER_IP=$(terraform output -raw server_ip)
        VOLUME_MOUNT=$(terraform output -raw volume_mount)

        echo -e "${GREEN}Server provisioned: ${SERVER_IP}${NC}"
        echo ""
        echo -e "${YELLOW}[2/2] Ansible configure + deploy...${NC}"
        run_ansible "$SERVER_IP" "$VOLUME_MOUNT"
        ;;

    ansible)
        # Server already provisioned — read IP from TF state or env
        if [ -n "${SERVER_IP:-}" ]; then
            IP="$SERVER_IP"
            MOUNT="${VOLUME_MOUNT:-/mnt/urwort-data}"
        else
            cd "$TF_DIR"
            IP=$(terraform output -raw server_ip 2>/dev/null || echo "")
            MOUNT=$(terraform output -raw volume_mount 2>/dev/null || echo "/mnt/urwort-data")
        fi

        if [ -z "$IP" ]; then
            echo -e "${RED}Cannot find server IP.${NC}"
            echo "Either set SERVER_IP env var or run terraform apply first."
            exit 1
        fi

        run_ansible "$IP" "$MOUNT"
        ;;

    sync)
        # Sync latest code changes + rebuild + restart — no system changes
        echo -e "${YELLOW}Syncing code to server and restarting services...${NC}"
        if [ -n "${SERVER_IP:-}" ]; then
            IP="$SERVER_IP"
            MOUNT="${VOLUME_MOUNT:-/mnt/urwort-data}"
        else
            cd "$TF_DIR"
            IP=$(terraform output -raw server_ip 2>/dev/null || echo "")
            MOUNT=$(terraform output -raw volume_mount 2>/dev/null || echo "/mnt/urwort-data")
        fi

        if [ -z "$IP" ]; then
            echo -e "${RED}Cannot find server IP.${NC}"
            echo "Either set SERVER_IP env var or run terraform apply first."
            exit 1
        fi

        run_ansible "$IP" "$MOUNT" "deploy"
        ;;

    destroy)
        echo -e "${RED}⚠️  This will destroy all infrastructure!${NC}"
        read -r -p "Type 'yes' to confirm: " confirm
        [ "$confirm" != "yes" ] && echo "Aborted." && exit 0
        cd "$TF_DIR"
        terraform destroy
        ;;

    *)
        echo "Usage: $0 [plan|apply|ansible|sync|destroy]"
        echo ""
        echo "  sync    — sync code + rebuild + restart (day-to-day)"
        echo "  ansible — full configure + deploy to existing server"
        echo "  apply   — provision infra + configure server + deploy app"
        echo "  plan    — preview terraform changes"
        echo "  destroy — tear down all infrastructure"
        exit 1
        ;;
esac
