#!/bin/bash
# ============================================================
# infra/scripts/setup-keys.sh
#
# One-time setup: generate the urwort SSH deploy key, write it
# to ~/.ssh/ and symlink it into infra/deploy-keys/ so the ops
# container can mount it.
#
# Also writes/updates infra/.env.keys with the public key and
# key paths — useful to source in CI or ops workflows.
#
# Usage:
#   ./infra/scripts/setup-keys.sh          # generate new key
#   ./infra/scripts/setup-keys.sh --force  # overwrite existing key
# ============================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INFRA_DIR="$ROOT_DIR/infra"
KEYS_DIR="$INFRA_DIR/deploy-keys"
ENV_KEYS="$INFRA_DIR/.env.keys"

SSH_KEY="$HOME/.ssh/urwort_ed25519"
SSH_PUB="$HOME/.ssh/urwort_ed25519.pub"
KEY_COMMENT="urwort-deploy-$(hostname)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true

echo -e "${GREEN}━━━ urwort deploy-key setup ━━━${NC}"
echo ""

# ── Step 1: Generate key pair ──────────────────────────────────────────────────
if [ -f "$SSH_KEY" ] && [ "$FORCE" = false ]; then
    echo -e "${YELLOW}Key already exists at $SSH_KEY${NC}"
    echo "  Use --force to overwrite."
    echo ""
else
    echo -e "${YELLOW}Generating ED25519 deploy key...${NC}"
    ssh-keygen -t ed25519 -C "$KEY_COMMENT" -f "$SSH_KEY" -N "" -q
    chmod 600 "$SSH_KEY"
    chmod 644 "$SSH_PUB"
    echo -e "  ${GREEN}✓ Key generated: $SSH_KEY${NC}"
    echo ""
fi

# ── Step 2: Symlink into infra/deploy-keys/ ────────────────────────────────────
mkdir -p "$KEYS_DIR"
ln -sf "$SSH_KEY"  "$KEYS_DIR/urwort_ed25519"
ln -sf "$SSH_PUB"  "$KEYS_DIR/urwort_ed25519.pub"
echo -e "  ${GREEN}✓ Symlinked into infra/deploy-keys/${NC}"
echo ""

# ── Step 3: Write infra/.env.keys ─────────────────────────────────────────────
PUB_KEY_CONTENT="$(cat "$SSH_PUB")"

cat > "$ENV_KEYS" << EOF
# ============================================================
# urwort deploy key paths — auto-generated by setup-keys.sh
# Source this file or read it in scripts that need key info.
# This file is gitignored — never commit it.
# ============================================================

URWORT_SSH_KEY=$SSH_KEY
URWORT_SSH_PUB=$SSH_PUB

# Public key value (paste this into Hetzner Console → SSH Keys,
# or add to the server's ~/.ssh/authorized_keys manually):
URWORT_SSH_PUB_KEY="$PUB_KEY_CONTENT"
EOF

chmod 600 "$ENV_KEYS"
echo -e "  ${GREEN}✓ Written: infra/.env.keys${NC}"
echo ""

# ── Step 4: Print public key and next steps ────────────────────────────────────
echo -e "${CYAN}━━━ Public key (add to Hetzner Console or server) ━━━${NC}"
echo ""
cat "$SSH_PUB"
echo ""
echo -e "${CYAN}━━━ Next steps ━━━${NC}"
echo ""
echo "  1. Add the public key above to Hetzner Console:"
echo "     https://console.hetzner.cloud → Project → Security → SSH Keys"
echo "     (Terraform will reference it as 'urwort-deploy')"
echo ""
echo "  2. Copy infra/.env.ops.example → infra/.env.ops and fill in HCLOUD_TOKEN:"
echo "     cp $INFRA_DIR/.env.ops.example $INFRA_DIR/.env.ops"
echo "     \$EDITOR $INFRA_DIR/.env.ops"
echo ""
echo "  3. Launch the ops container:"
echo "     ./ops.sh"
echo ""
echo "  4. Inside the container, provision the server:"
echo "     ./scripts/deploy.sh apply"
echo ""
echo -e "${GREEN}━━━ Setup complete ━━━${NC}"
